-- MySQL Script generated by MySQL Workbench
-- Wed Aug  8 10:53:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SGI` ;

-- -----------------------------------------------------
-- Schema SGI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGI` DEFAULT CHARACTER SET utf8 ;
USE `SGI` ;

-- -----------------------------------------------------
-- Table `SGI`.`congrecacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`congrecacao` ;

CREATE TABLE IF NOT EXISTS `SGI`.`congrecacao` (
  `id_congrecacao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_congrecacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`funcao` ;

CREATE TABLE IF NOT EXISTS `SGI`.`funcao` (
  `id_funcao` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_funcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`membro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`membro` ;

CREATE TABLE IF NOT EXISTS `SGI`.`membro` (
  `id_membro` INT NOT NULL,
  `id_funcao` INT NOT NULL,
  `id_congrecacao` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `rg` VARCHAR(15) NULL,
  `cpf` VARCHAR(15) NULL,
  `data_batismo` DATETIME NULL,
  `data_admissao` DATETIME NULL,
  `pai` VARCHAR(100) NULL,
  `mae` VARCHAR(100) NULL,
  `sexo` CHAR(1) NULL,
  `naturalidade` VARCHAR(50) NULL,
  `procedencia` VARCHAR(50) NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_membro`),
  INDEX `fk_membro_funcao_idx` (`id_funcao` ASC),
  INDEX `fk_membro_congrecacao1_idx` (`id_congrecacao` ASC),
  CONSTRAINT `fk_membro_funcao`
    FOREIGN KEY (`id_funcao`)
    REFERENCES `SGI`.`funcao` (`id_funcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_congrecacao1`
    FOREIGN KEY (`id_congrecacao`)
    REFERENCES `SGI`.`congrecacao` (`id_congrecacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`perfil` ;

CREATE TABLE IF NOT EXISTS `SGI`.`perfil` (
  `id_perfil` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`usuario` ;

CREATE TABLE IF NOT EXISTS `SGI`.`usuario` (
  `id_usuario` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_perfil1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `SGI`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `SGI`.`fornecedor` (
  `id_fornecedor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `contato` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`tipo_movimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`tipo_movimento` ;

CREATE TABLE IF NOT EXISTS `SGI`.`tipo_movimento` (
  `id_tipo_movimento` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_tipo_movimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `SGI`.`pagamento` (
  `id_pagamento` INT NOT NULL,
  `id_tipo_movimento` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  `id_congrecacao` INT NOT NULL,
  `data_prevista` DATETIME NOT NULL,
  `data_realizada` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_pagamento_tipo_movimento1_idx` (`id_tipo_movimento` ASC),
  INDEX `fk_pagamento_fornecedor1_idx` (`id_fornecedor` ASC),
  INDEX `fk_pagamento_congrecacao1_idx` (`id_congrecacao` ASC),
  CONSTRAINT `fk_pagamento_tipo_movimento1`
    FOREIGN KEY (`id_tipo_movimento`)
    REFERENCES `SGI`.`tipo_movimento` (`id_tipo_movimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `SGI`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_congrecacao1`
    FOREIGN KEY (`id_congrecacao`)
    REFERENCES `SGI`.`congrecacao` (`id_congrecacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`recebimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`recebimento` ;

CREATE TABLE IF NOT EXISTS `SGI`.`recebimento` (
  `id_recebimento` INT NOT NULL,
  `id_tipo_movimento` INT NOT NULL,
  `id_membro` INT NOT NULL,
  `id_congrecacao` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`id_recebimento`),
  INDEX `fk_recebimento_tipo_movimento1_idx` (`id_tipo_movimento` ASC),
  INDEX `fk_recebimento_membro1_idx` (`id_membro` ASC),
  INDEX `fk_recebimento_congrecacao1_idx` (`id_congrecacao` ASC),
  CONSTRAINT `fk_recebimento_tipo_movimento1`
    FOREIGN KEY (`id_tipo_movimento`)
    REFERENCES `SGI`.`tipo_movimento` (`id_tipo_movimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recebimento_membro1`
    FOREIGN KEY (`id_membro`)
    REFERENCES `SGI`.`membro` (`id_membro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recebimento_congrecacao1`
    FOREIGN KEY (`id_congrecacao`)
    REFERENCES `SGI`.`congrecacao` (`id_congrecacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`caixa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGI`.`caixa` ;

CREATE TABLE IF NOT EXISTS `SGI`.`caixa` (
  `id_caixa` INT NOT NULL,
  `id_congrecacao` INT NOT NULL,
  `id_recebimento` INT NULL,
  `id_pagamento` INT NULL,
  `tipo` SMALLINT(1) NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id_caixa`),
  INDEX `fk_caixa_recebimento1_idx` (`id_recebimento` ASC),
  INDEX `fk_caixa_pagamento1_idx` (`id_pagamento` ASC),
  INDEX `fk_caixa_congrecacao1_idx` (`id_congrecacao` ASC),
  CONSTRAINT `fk_caixa_recebimento1`
    FOREIGN KEY (`id_recebimento`)
    REFERENCES `SGI`.`recebimento` (`id_recebimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_pagamento1`
    FOREIGN KEY (`id_pagamento`)
    REFERENCES `SGI`.`pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_congrecacao1`
    FOREIGN KEY (`id_congrecacao`)
    REFERENCES `SGI`.`congrecacao` (`id_congrecacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
